---
# defaults file for users

# users home directory
users_home: /home

# default user's home directory permissions
users_home_mode: "0755"

# default user's ssh key type
users_ssh_key_type: rsa

# default user's ssh key bits
users_ssh_key_bits: 2048

# default user's setting for authorized keys exclusive
users_authorized_keys_exclusive: no

# list of users to be removed
users_remove: []
