---

- name: Copy the issue
  become: yes
  copy:
    src: issue
    dest: /etc/issue
    mode: 0644 
  tags:
    - issue
    - base

- name: Copy the issue.net
  become: yes
  copy:
    src: issue.net
    dest: /etc/issue.net
    mode: 0644      
  tags:
    - issue
    - base