---

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

  tags:
    - configuration
    - base


  - name: Install standard base packages
    yum: name={{ item }} state=installed
    with_items:
      "{{ base_packages }}"

  tags:
    - configuration
    - base