---

- name: Disable selinux
  become: yes
  selinux: state=disabled

  tags:
    - configuration
    - base

- name: Set SELinux in permissive mode until the machine is rebooted
  command: setenforce 0
  ignore_errors: true
  changed_when: false

  tags:
    - configuration
    - base

- name: Role Disable Security-Enhanced Linux (SELinux)
  become: yes
  template:
    src: config.j2
    dest: /etc/selinux/config
    force: yes
    backup: no
    owner: root
    group: root
    mode: 0644

  tags:
    - configuration
    - base
